### PR TITLE
update to newer mongo driver

### PR DESCRIPTION
**Pull request by maximshe**
Fix of #14

### CODE REVIEW

**Comment by maximshe** [comment]
With this update we also could start using this module with latest node.js version

**Comment by mcdonnelldean** [comment]
@geek Can you review this? Looks good but just to be sure.

**Comment by geek** [comment]
LGTM

**Comment by chafnan** [comment]
The dep in the npm package is set to `"mongodb": "~1.4.30"`.  Can the npm package get updated?

**Pull request merged**
